// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PhoneStore.Data;

#nullable disable

namespace PhoneStore.Migrations
{
    [DbContext(typeof(PhoneStoreContext))]
    [Migration("20251121125655_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("PhoneStore.Models.Phone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Specifications")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Phones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Apple",
                            Description = "iPhone 15 Pro Max với chip A17 Pro mạnh mẽ",
                            ImageUrl = "/images/iphone15.jpg",
                            Name = "iPhone 15 Pro Max",
                            Price = 29990000m,
                            Specifications = "6.7 inch, 256GB, Camera 48MP",
                            Stock = 50
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Samsung",
                            Description = "Galaxy S24 Ultra với S Pen tích hợp",
                            ImageUrl = "/images/s24ultra.jpg",
                            Name = "Samsung Galaxy S24 Ultra",
                            Price = 26990000m,
                            Specifications = "6.8 inch, 256GB, Camera 200MP",
                            Stock = 40
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Xiaomi",
                            Description = "Xiaomi 14 Pro camera Leica chuyên nghiệp",
                            ImageUrl = "/images/xiaomi14.jpg",
                            Name = "Xiaomi 14 Pro",
                            Price = 18990000m,
                            Specifications = "6.73 inch, 256GB, Camera 50MP",
                            Stock = 60
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
